# Generated by Django 4.1.3 on 2022-11-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
